name: Alvin Crespo
markdown: redcarpet
pygments: true

# Setup
title:            Alvin Crespo
tagline:          'Software Engineer'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://alvincrespo.me